### ISSUE TITLE
Strange info popups (inside comments) LSP/VSCODE

### ISSUE THREAD

**Issue by dennybaa** [kcl-lang/kcl#1530] opened 2024-07-31 10:10 UTC
Hello,

this is the weird output, it looks like this:

![Screenshot from 2024-07-31 13-06-12](https://github.com/user-attachments/assets/7e578daa-834d-48be-96cc-07572d0753aa)

In other words it breaks the actual comment line...

_Actually, things go bizarre for a while like on the screenshots, restart of vscode brings it back to normal._

**Comment by dennybaa** [comment] 2024-07-31 10:30
More quirks, see the boolkey
![Screenshot from 2024-07-31 13-29-15](https://github.com/user-attachments/assets/15db9a02-2a1c-4694-bee8-06d7ef989214)

**Comment by He1pa** [comment] 2024-08-05 02:42
> More quirks, see the boolkey ![Screenshot from 2024-07-31 13-29-15](https://private-user-images.githubusercontent.com/891419/353796384-15db9a02-2a1c-4694-bee8-06d7ef989214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjU1NTcsIm5iZiI6MTcyMjgyNTI1NywicGF0aCI6Ii84OTE0MTkvMzUzNzk2Mzg0LTE1ZGI5YTAyLTJhMWMtNDY5NC1iZWU4LTA2ZDdlZjk4OTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwMjM0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIwOTNmZTkxYzI3NWRmZmU1NTc3OTZhYTAxYTVhM2I0N2Y2ZTg4NDI4MWMxOGYwNThmMTRkYjk4ZDYwN2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ga7YS6hxvOm4VDyGRYjTOle6hZ-lCXuPOvevTOyPQY)

Have you defined `boolkey`?

**Comment by He1pa** [comment] 2024-08-05 03:41
And, can you provide some step to reproduce it?

**Comment by He1pa** [comment] 2024-08-06 09:57
I can't reproduce it, but I'm trying to fix this in https://github.com/kcl-lang/vscode-kcl/pull/59.
Temporarily close this issue, if you still have problems, you can reopen it

**Closed by He1pa** 2024-08-06 09:57 UTC
Labels: bug, lsp

**Comment by dennybaa** [comment] 2024-08-06 22:02
@He1pa Sure I will. Thank you! 
Regarding ...
> Have you defined boolkey?

I have no idea why this "glitching" comes in. But the boolkey is the result of splitting the informational output ... " _debug ... book ... key". Plz, have a look at the grayed info notes.

**Comment by Peefy** [comment] 2026-08-26 14:31
Closing per @He1pa's direction: "I can't reproduce it, but I'm trying to fix this in https://github.com/kcl-lang/vscode-kcl/pull/59. Temporarily close this issue, if you still have problems, you can reopen it."

The visual glitch (info popup inside a comment line, "_debug ... : bool ... key:" appearing split) is a VSCode-extension rendering issue, not something the KCL language server contributes to. The fix is being tracked in the kcl-vscode extension repo (PR kcl-lang/vscode-kcl#59).

If anyone can confirm the merged extension release still exhibits this glitch after vscode-kcl#59 lands, please reopen with a screenshot and current kcl-language-server version.
