### ISSUE TITLE
[Bug][LSP] completion on right side value of binary expression

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#824] opened 2023-11-01 02:12 UTC
## Enhancement

the completion on right side value of binary expression sometimes failed:
![2](https://github.com/kcl-lang/kcl/assets/29722609/4a184d18-51ef-4a06-bf79-0e5fc4b74ad4)

the left side completion works well:

![3](https://github.com/kcl-lang/kcl/assets/29722609/982dd503-c7ab-4f78-847a-91e8e28de8ad)

sometimes the right side completion works as expected:

![1](https://github.com/kcl-lang/kcl/assets/29722609/dfe4c81d-2945-40eb-9d6c-d7ea11fb8b68)

**Comment by He1pa** [comment] 2023-11-28 06:45
fixed by: https://github.com/kcl-lang/kcl/pull/886

**Comment by Peefy** [comment] 2023-11-29 14:07
The issue is still existed in kcl v0.7.0-beta.2

**Closed** 2023-12-06 09:29 UTC
Labels: lsp
